cloudblue/connect-haxe-sdk

Packager.hx
connect/Env.hx
connect/F.hx
connect/Flow.hx
connect/Processor.hx
connect/StepStorage.hx
connect/api/impl/ApiClientImpl.hx
connect/logger/FileLoggerWriter.hx
connect/logger/ILoggerFormatter.hx
connect/logger/ILoggerWriter.hx
connect/logger/Logger.hx
connect/logger/LoggerConfig.hx
connect/logger/LoggerOutput.hx
connect/logger/MarkdownLoggerFormatter.hx
connect/models/AssetRequest.hx
examples/Example.hx
examples/Example.java
examples/example.js
examples/example.php
examples/example.py
tests/unit/MarkdownLoggerFormatterTest.hx

Now Logger is configured by passing it an instance of LoggerConfig instead of a lot of parameters.
LoggerConfig accepts multiple log outputs now, each with a pair of ILoggerFormatter and ILoggerWriter.

Cusdk 41 logger options

---

.travis.yml
connect/logger/LoggerConfig.hx
stuff/after_script.sh
stuff/before_script.sh
stuff/gitignore_java

Push Java code to connect-java-sdk repo when commiting to master.

Cusdk 51 push java code

---

Packager.hx
connect/Flow.hx
connect/Processor.hx
connect/api/impl/ApiClientImpl.hx
connect/logger/Logger.hx
connect/logger/LoggerConfig.hx
connect/logger/LoggerHandler.hx

Now, within the given logs folder, a subfolder with the product id is created to store the log files related to that product. Within it, it works as before: one log file per asset, tier config, or usage file.

Cusdk 56 prd log subfolder

---

.travis.yml
stuff/push_tag.py

Fixes on how a tag is being pushed (only when pushing to master).

Quick travis fix

---

connect/util/DateTime.hx
test/unit/DateTimeTest.hx

Dates can now be compared with the methods `DateTime.compare` and `DateTime.equals`.

CUSDK-65 Added comparison of dates.

---

connect/Flow.hx
connect/api/ITierApi.hx
connect/api/impl/TierApiImpl.hx
connect/models/Agreement.hx
connect/models/AssetRequest.hx
connect/models/Listing.hx
connect/models/Marketplace.hx
connect/models/Model.hx
connect/models/TierConfigRequest.hx
connect/models/UsageFile.hx
connect/util/Util.hx
test/mocks/TierApiMock.hx
test/unit/AgreementTest.hx
test/unit/AssetRequestTest.hx
test/unit/ListingTest.hx
test/unit/MarketplaceTest.hx
test/unit/TierConfigRequestTest.hx
test/unit/UsageFileTest.hx

When an update or put method call is done on a resource, only the fields whose value has changed is sent to Connect, independently on whether you are using the flows architecture or not.

Cusdk 69 send diff

---

connect/api/ITierApi.hx
connect/api/impl/TierApiImpl.hx
connect/models/TierConfigRequest.hx
test/mocks/TierApiMock.hx
test/mocks/data/usagefile_list.json
test/unit/TierConfigRequestTest.hx
test/unit/UsageFileTest.hx

TierConfigRequest.approveByTemplate and approveByTile do not have a response. As they are trying to parse a response, an exception is raised.

Cusdk 76 tcr approve

---

connect/Env.hx
connect/api/Query.hx
test/unit/QueryTest.hx
test/unit/TestSuite.hx

Added Env.initDefaultQuery, Env.isDefaultQueryInitialized, and Query.default_ methods.

CUSDK-78-default-query

---

connect/models/Constraints.hx
connect/models/Param.hx
test/unit/QueryTest.hx

Added missing fields in Param class.

CUSDK-79-product-params

---

connect/util/Dictionary.hx

Fixed small bug when parsing indented Python dicts.

CUSDK-87 (again)

---

connect/models/Asset.hx
connect/models/TierAccount.hx
connect/util/DateTime.hx
test/unit/AssetTest.hx
test/unit/DateTimeTest.hx
test/unit/TestSuite.hx

* Add DateTime.getTimestamp.
* Add TierAccount.getTierConfig.
* Add Asset.getCustomerConfig.
* Add Asset.getTier1Config.
* Asset Asset.getTier2Config.

Cusdk 91 small additions

---

connect/Flow.hx
connect/api/impl/ApiClientImpl.hx
connect/logger/Logger.hx
connect/logger/MarkdownLoggerFormatter.hx
connect/native/JavaIterator.hx
connect/util/Collection.hx

* Java hanging on http request fix.
* Fixed bug when getting TierAccount id when processing TierConfigRequest.

Cusdk 104 java https

---

connect/Flow.hx

Added new step param to allow tier flows being saved on connect.

Cusdk 106 tier step param

---

.travis.yml
connect/models/Model.hx
connect/models/Param.hx
test/mocks/data/request_list.json
test/unit/AssetTest.hx

Added support for structured_value field of Param models.

Cusdk 110 param checkbox

---

.travis.yml
connect/models/Conversation.hx

Fixed exception when calling Conversation.createMessage and the "messages" field contains null.

CUSDK-111 Create message exception.

---

Connect.hx
connect/models/Marketplace.hx
connect/models/UsageCategory.hx
connect/models/UsageFile.hx
connect/models/UsageParam.hx
connect/models/UsageRecord.hx
connect/util/ExcelWriter.hx
connect/util/Util.hx
test/unit/UsageFileTest.hx

Categories can be added to a usage file now. Also, UsageRecords can have a collection of UsageParam objects in its "params" field, which represent custom columns.

Cusdk 112 usage categories

---

connect/api/Query.hx
connect/util/ExcelWriter.hx
test/unit/QueryTest.hx

Query.toPlain() now adds ordering filter to query params if it exists. Also, all Array parameters have been replaced with Collection.

Cusdk 113 query plain ordering

---

connect/api/ConnectHelper.hx
connect/api/IGeneralApi.hx
connect/api/impl/FulfillmentApiImpl.hx
connect/api/impl/GeneralApiImpl.hx
connect/api/impl/MarketplaceApiImpl.hx
connect/api/impl/TierApiImpl.hx
connect/api/impl/UsageApiImpl.hx
connect/models/Product.hx
test/mocks/GeneralApiMock.hx
test/unit/ProductTest.hx

Include parameter creation, listing with filters, etc functionality added in new Connect v20 into Product model.

Cusdk 81 product params

---

connect/util/Blob.hx

CUSDK-126: Blob.save

---

.travis.yml
connect/models/AssetRequest.hx
connect/models/TierConfigRequest.hx
test/unit/AssetRequestTest.hx
test/unit/AssetTest.hx
test/unit/TierConfigRequestTest.hx
test/unit/data/requests.json
test/unit/data/tierconfigrequests.json

Fixing problem when updating a request that has set value_error in some params to an empty string and value has not changed.

Cusdk 128 update error

---

.travis.yml
connect/Flow.hx

Now, requests are updated automatically before skipping.

CUSDK-133: Request does not update fulfillment parameters when raising a exception Edit Comment AssignMore Start progressResolve IssueWorkflow Export.

---

.travis.yml
connect/Flow.hx
connect/storage/StepData.hx

Added Flow.setSkipRequestOnPendingMigration() method to allow disabling autoskip of requests when migration is pending on the request.

Cusdk 135 disable migration autoskip

---

connect/Flow.hx
connect/logger/Logger.hx
test/unit/LoggerTest.hx

Give logger the possibility to change the log path based on the given object of the next models:
- Asset
- AssetRequest
- TierconfigRequest
- Listing
- UsageFile

CUSDK-140: Add method to allow modify log path using diferent models

---

connect/Flow.hx

setData does not work in setup() Flow method

[CUSDK-146] Fix setData on setup

---

connect/api/ConnectHelper.hx
connect/api/GeneralApi.hx
connect/api/IApiClient.hx
connect/api/impl/ApiClientImpl.hx
test/unit/AccountTest.hx
test/unit/AgreementTest.hx
test/unit/AssetRequestTest.hx
test/unit/AssetTest.hx
test/unit/CategoryTest.hx
test/unit/ConfigurationTest.hx
test/unit/ConversationTest.hx
test/unit/FlowAttemptsTest.hx
test/unit/FlowTest.hx
test/unit/ItemTest.hx
test/unit/ListingRequestTest.hx
test/unit/ListingTest.hx
test/unit/MarketplaceTest.hx
test/unit/ProductTest.hx
test/unit/SubscriptionRequestTest.hx
test/unit/SubscriptionTest.hx
test/unit/TierAccountTest.hx
test/unit/TierConfigRequestTest.hx
test/unit/TierConfigTest.hx
test/unit/UsageFileTest.hx

Conversations should be printed in INFO mode.

Cusdk 145: Conversations should be printed in INFO mode.

---

.travis.yml
connect/Env.hx
connect/api/ConnectHelper.hx
connect/api/GeneralApi.hx
connect/logger/Logger.hx
connect/models/Model.hx
connect/native/JavaIterator.hx
connect/storage/StepData.hx
connect/util/Collection.hx
connect/util/Util.hx
stuff/deploy_maven_central.py
test/unit/StepStorageTest.hx

The previous PR with this ticket was not working correctly, because ConnectHelper.connectSyncRequest was not actually sending the logging level to the Api Client.
Also, calls to Std.is have been replaced with Std.isOfType, to avoid warnings on Haxe 4.2.0.

Cusdk 145 conversations debug logging

---

connect/api/FulfillmentApi.hx
connect/api/GeneralApi.hx
connect/api/MarketplaceApi.hx
connect/api/SubscriptionsApi.hx
connect/api/TierApi.hx
connect/api/UsageApi.hx

Modify list operations to print responses only on DEBUG level.

CUSDK-161: List operation prints large logs

---

connect/models/Agreement.hx
connect/models/AssetRequest.hx
connect/models/Marketplace.hx
connect/models/TierConfigRequest.hx
connect/models/UsageFile.hx

All the update methods now capture possible exceptions and return null in that case.

CUSDK-175: update methods now capture exceptions

---

connect/flow/FlowLogger.hx
connect/util/Util.hx

Fixed FlowLogger.getFormattedRequest so logs are properly masked.

CUSDK-179: Params not getting correctly masked.

---

connect/Flow.hx
connect/Processor.hx
connect/flow/FlowExecutor.hx
connect/logger/Logger.hx
connect/logger/LoggerConfig.hx

Full stack trace should only go to the log.

CUSDK-184: Conversations should only get exception message on skip

---

connect/util/Collection.hx

Implemented missing methods in Collection to make it a fully supported Iterable in Java.

CUSDK-185-java-iterable-missing-methods

---

connect/models/TierConfigRequest.hx

Added fix for TRC with no param property.

CUSK-187 Error on getModifiedTcrParams
