cloudblue/connect-haxe-sdk

connect/Flow.hx

Request is only updated automatically on approval if the asset or TCR params have changed.
To review the code, have in mind that "request" and "tcr" vars contain instances of AssetRequest and TierConfigRequest which only carry the changes performed on the resource, so if the contained asset or params have not changed, then these fields are null.

CUSDK-50-update-request-changes

---

connect/Flow.hx
connect/api/Query.hx
connect/models/AssetRequest.hx
connect/models/TierConfigRequest.hx
connect/util/Collection.hx
test/unit/AssetRequestTest.hx
test/unit/FlowTest.hx
test/unit/Helper.hx
test/unit/TierConfigRequestTest.hx

Add a Collection<Param> parameter to Flow.inquire and request update methods:
- Flow.inquire
- AssetRequest.update
- TierConfigRequest.update
You can pass null as argument, in which case the parameters that have changed since the request was pulled will be uploaded (this is the current functionality).
Also, Query class now exports RQL requests putting keys in alphabetical order, to simplify unit testing.

Cusdk 95 inquire params

---

.gitignore
connect/Env.hx
connect/Flow.hx
connect/api/impl/ApiClientImpl.hx
connect/logger/ILoggerFormatter.hx
connect/logger/Logger.hx
connect/logger/LoggerConfig.hx
connect/logger/MarkdownLoggerFormatter.hx
connect/logger/PlainLoggerFormatter.hx
connect/util/Util.hx
test/unit/CustomLoggerFormatterTest.hx
test/unit/MarkdownLoggerFormatterTest.hx
test/unit/TestSuite.hx
test/unit/UsageFileTest.hx

Added a PlainLoggerFormatter which conforms to the specification here: https://confluence.int.zone/pages/viewpage.action?pageId=944671602#id-08-ConnectSalesModels(DirectvsDistribution)-LogsStructure.
This is now the default formatter for connectors. In order to enable MarkdownLoggerFormatter, it is possible to call `markdown(true)` on the LoggerConfig object.

Cusdk 100 plain logger formatter

---

connect/Flow.hx
connect/models/TierConfigRequest.hx
test/mocks/data/tierconfigrequest_list.json
test/unit/TestSuite.hx
test/unit/TierConfigRequestTest.hx

When updating a TierConfigRequest, only params are being updated, but not configuration.params nor configuration.configuration.params. Now all the modified parameters are moved to the params array of the TCR before being updated.
Also, the path of logs when processing TCRs have been fixed.

Cusdk 109 update tier params

---

connect/models/TierConfigRequest.hx
examples/example.py

TCR approved by template were using same parameter that asset request `{'template_id': id}`, but body format for TCR is different `{'template': {'id': id}}`.

CUSDK-124: TCR approved by template are not correct

---

connect/Flow.hx
connect/api/impl/ApiClientImpl.hx
connect/logger/Logger.hx
connect/logger/LoggerConfig.hx
connect/util/Util.hx
test/unit/LoggerTest.hx
test/unit/ModelTest.hx

LoggerConfig now has a `beautify(enable:Bool)` method (which defaults to `true`), that will disable beautification of JSON data in log messages, allowing them to fit in a single line.

CUSDK-121: disable Logger beautifier.

---

connect/logger/Logger.hx
connect/logger/PlainLoggerFormatter.hx

When a second processor is run, the request id was not being reset to NO_REQUEST. Also, filenames were getting duplicated on each processor ('global.log', 'global.log.log', etc).

CUSDK-125: Removed propagation of request id and duplication of log filename extension across processors

---

connect/api/Query.hx
test/unit/QueryTest.hx

Added Query.forceRql() method to force RQL filters even on APIs that use plain query params by default.

CUSDK-122: Query.forceRql()

---

connect/Flow.hx

Different tier parameters (__sdk_processor_step_tier) are required to manage tier config request from different tier level(Tier1 and Tier2), the parameter cannot be the same for both.

CUSDK-129: Create different __sdk_processor_step_tier parameter for different tier levels

---

connect/Flow.hx
connect/models/AssetRequest.hx
connect/models/TierConfigRequest.hx
test/unit/AssetRequestTest.hx
test/unit/TierConfigRequestTest.hx

When a request update does not contain a value field for a Param, the value is set to null in Connect, so an update has been made to always send the value of the param.

Cusdk 130 update parameter

---

.travis.yml
connect/logger/Logger.hx
connect/logger/LoggerConfig.hx
connect/models/Param.hx
connect/util/Util.hx
test/unit/LoggerTest.hx

Apart from LoggerConfig.maskedFields, which masks JSON objects based on key names, I have added LoggerConfig.maskedParams, which allows masking a param value based on the param id. Also, value of params of type "password" is automatically masked too.

Cusdk 131 mask connect params

---

.travis.yml
connect/util/DateTime.hx

Fixed crash in DateTime.fromString when trying to parse some weirdly formed strings which do not contain a valid date.

Cusdk 143 datetime crash

---

connect/Flow.hx
connect/Processor.hx
connect/flow/FlowExecutor.hx

In case you need some data in the Flow not to be stored when processing fails, Flow now has the setVolatileData method, which allows exactly for that: define request-specific data which won't be stored.

CUSDK-136: Add Flow.setVolatileData

---

connect/models/TierConfigRequest.hx
connect/util/Util.hx

Now if the TierConfig or Configuration related to a TierConfigRequest have parameters with the same name as ones present in the TCR, they are not added to the parameter list to update, so they do not appear duplicated in the request.

CUSDK-148: TierConfigRequest.update duplicated parameters error.

---

connect/api/UsageApi.hx
test/unit/UsageFileTest.hx

Usage Files API now uses RQL filters instead of plain query params.

CUSDK-151: RQL in Usage files API

---

connect/api/ConnectHelper.hx
connect/api/IApiClient.hx
connect/api/impl/ApiClientImpl.hx
connect/models/AssetRequest.hx
connect/models/Conversation.hx
test/unit/AccountTest.hx
test/unit/AgreementTest.hx
test/unit/AssetRequestTest.hx
test/unit/AssetTest.hx
test/unit/CategoryTest.hx
test/unit/ConfigurationTest.hx
test/unit/ConversationTest.hx
test/unit/FlowAttemptsTest.hx
test/unit/FlowTest.hx
test/unit/ItemTest.hx
test/unit/ListingRequestTest.hx
test/unit/ListingTest.hx
test/unit/MarketplaceTest.hx
test/unit/ProductTest.hx
test/unit/SubscriptionRequestTest.hx
test/unit/SubscriptionTest.hx
test/unit/TierAccountTest.hx
test/unit/TierConfigRequestTest.hx
test/unit/TierConfigTest.hx
test/unit/UsageFileTest.hx

The signature of some public method had changed to receive a request or logger level. A new version of the method receiving those has been added, while the original method has remained untouched for backwards compatibility.

CUSDK-152: Reverted changes in some public method signatures

---

Connect.hx
connect/Flow.hx
connect/flow/FlowExecutor.hx

If you abort a request in the Flow's setup() method, the next request will begin with aborted status in the setup() method, and won't reset it until the first step. This fixes the issue by making sure that every time the setup() method executes, status from previous request is reset.

CUSDK-158: Abort status is not reset after finishing a request.

---

connect/Flow.hx
connect/api/ConnectHelper.hx
connect/api/FulfillmentApi.hx
connect/api/GeneralApi.hx
connect/api/MarketplaceApi.hx
connect/api/TierApi.hx
connect/api/UsageApi.hx
connect/api/impl/ApiClientImpl.hx
connect/flow/FlowLogger.hx
connect/models/Asset.hx
connect/models/AssetRequest.hx
connect/models/Conversation.hx
connect/models/Listing.hx
connect/models/TierConfigRequest.hx
connect/models/UsageFile.hx

When using a Flow, the requests performed by the flow itself have the correct prefix in the log, but other Connect calls you might perform (like Product.get) don't. Now, ConnectHelper is aware of the context where the flow is running (since the flow sets the correct logger for it every time a new request begins processing), so all calls will be correctly logged.

CUSDK-155: Add request prefix to all logs when a flow is running.

---

connect/Env.hx
connect/api/ConnectHelper.hx

Storing the root logger in the ConnectHelper on startup causes the logger to be initialized, so any further attempts to init the logger will raise an exception. This defers the retrieval of the log on the ConnectHelper side until th efirst time it is actually used.

CUSDK-155: Fixed logger being automatically initialized on program start.

---

connect/models/AssetRequest.hx

This is to add support for https://confluence.int.zone/display/ARD/Delegation+Of+Fulfillment+To+Connect+Processors#DelegationOfFulfillmentToConnectProcessors-ChangeRequestforProcessors

CUSDK-176: Use "migration_info_object" as well as "migration_info" for skipping

---

.travis.yml
connect/models/TierConfigRequest.hx
stuff/push_tag.py

This contains a bugfix for the TierConfigRequest.update method when the TCR params array has been modified by hand. This PR backports the fix to the 20.x version of the SDK.

CUSDK-178: TierConfigRequest.update fix (v20 backport)
